spring:
  datasource:
    driver-class-name: ***********driver-class-name************
    url: *********URL***********
    username: ****USERNAME****
    password: *****PASSWORD*****
    hikari:
      connectionTestQuery: ***********
      connection-timeout: ************
      idle-timeout: **********
      max-lifetime: *********
      validation-timeout: ********
      maximum-pool-size: **********
      minimum-idle: *************
mybatis-plus:
  configuration:
    log-impl: 
app:
  verification:
    enabled: 
  admin:
    email: *********ADMINEMAIL********* # 管理员邮箱
